# Generated by Django 5.0.6 on 2024-06-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='prescription',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
