# Generated by Django 5.0.6 on 2024-06-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_specialty_options_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='timestamp_end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='timestamp_start',
        ),
    ]
